fail = open("viga.txt", encoding="UTF-8")
lause = fail.read()
lause = lause.replace(" aga ", ", aga ")
lause = lause.replace(" et ", ",  et ")
lause = lause.replace(" sest ", ", sest ")
lause = lause.replace(" kuid ", ", kuid ")
fail2= open("para.txt", "w", encoding="UTF-8")
fail2.write(lause)
fail.close()
fail2.close()